services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_HOST=127.0.0.1
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=crud
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
        test: ["CMD-SHELL", "mysqladmin -h 'localhost' -u root -pWelcome123 ping --silent"]
        interval: 30s
        timeout: 30s
        retries: 3
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - dbnet

networks:
  dbnet:
    driver : bridge      